version: '2'
services:
    micoservicedemoapplication-app:
        image: micoservicedemoapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://micoservicedemoapplication-mysql:3306/micoservicedemoapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=micoservicedemoapplication-elasticsearch:9300
    micoservicedemoapplication-mysql:
        extends:
            file: mysql.yml
            service: micoservicedemoapplication-mysql
    micoservicedemoapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: micoservicedemoapplication-elasticsearch
